### ISSUE TITLE
Trending tab deprecated, due to be shutdown after 2022-09-30

### ISSUE THREAD

**Issue by dmke** [kawamataryo/github-trending-bot#7]
Just FYI, some kind soul mentioned your bot on [this Reddit comment](https://www.reddit.com/r/programming/comments/x3ph21/github_is_removing_the_trending_repositories_page/imrdgm6/?context=3):

![image](https://user-images.githubusercontent.com/327411/188166007-c0f7dc3f-0b66-4bbe-832a-d51fd3e2a689.png)

- https://github.com/community/community/discussions/31644

**Comment by kawamataryo** [comment]
what the hell !
I didn't know that. Thanks for telling me about it.

I'll try to think of an alternative.

**Comment by kawamataryo** [comment]
It might be okay.

https://github.com/community/community/discussions/31644#discussioncomment-3539690

**Comment by dmke** [comment]
Ah, that came to a conclusion very fast. I guess, I can close this issue then :)
